### ISSUE TITLE
BankingStage: Vote Threads

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2184]
### Problem
- BankingStage currently has 2 vote threads
- The vote threads share a storage that they both insert into
- Only one of the vote threads does actual processing, the other just receives and inserts into the shared storage
- Vote threads do not receive that many packets, compared to non-vote threads

### Proposed Solution
- Use a single unified vote thread that pulls from both gossip and tpu-vote channels.
- Simplify "shared" data-structure since it is now single-threaded and we do not need locks

### Plan

1. Begin by simplifying vote threads: 
  - [x] #5467 - Move vote processing loop to separate file vote_worker.rs 
  - [x] #5504 - Necessary state on VoteWorker
  - [x] #5535 - Move `Consumer` process loops to `VoteWorker`
  - [x] #5626 - Move processing loop from `VoteStorage` to `VoteWorker`
  - [x] #5726 - Remove extra loops in `VoteWorker`
  - [x] #5770 - State includes storage/container
2. Single vote thread worker
  - [ ] Get results from experiments with single vote thread

Misc PRs:
- [x] #5769
