### ISSUE TITLE
[Tracking] Scheduler Configurability

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2199]
### Problem
- Current scheduler behavior is pretty strict
- Variation in scheduler behavior can actually help network stability by making user-side attacks less reliable
- Some scheduler behavior would ideally be easily modified by the operators such that they can optimize for their use-case
- Ideally all this could be changed at runtime without restarting the validator; this would allow operators to more easily optimize their performance and/or behavior

### Proposed Solution

- [ ] Scheduler parameter configuration:
  - [ ] #4064 
  - [ ] #3947
- [ ] #2125
- [ ] Scheduler plugin: transaction prioritization
- [ ] Scheduler plugin: thread-selection

**Comment by apfitzge** [comment]
Closing in favor of scheduler-bindings approach to configurability
