### ISSUE TITLE
[Tracking] lock_accounts performance

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2289]
#### Problem

- #2262 added a benchmark for locking and unlocking accounts which is called before processing transactions in both block-verification and block-production
- The benchmark revealed that for transactions with many account-locks the performance is quite bad and is an unexpected bottleneck: ~200ktps w/ 64 accounts 

#### Proposed Solution

Improve performance. Test the following ideas:
- [x] #2105 
- [x] #2292
- [x] #2448
- [ ] Skip re-doing validation in block-production since we do it in the intial checks before buffering
- [ ] Consider removing per-batch allocations
- [ ] Shared map inside `AccountLocks` to avoid double-hashing
