### ISSUE TITLE
[Tracking] Async Block-Production and Block-Validation (Excluding Consensus)

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#2502]
### Problem

There have been long-term efforts towards enabling asynchronous block production and validation.
There are numerous changes required to enable this functionality, but there is currently no issue tracking what needs to be done.
This issue serves to track open tasks/projects in order to enable async or semi-async execution.

A specific note should be made that this is explicitly for block production and validation, and does not consider the consensus changes that are necessary for allowing for block validation to lag significantly behind the head of the chain.
This issue is only concerned with separating the necessity for execution and account-state from block validity.

### Proposed Solution

Each item links to a proposal or tracking issue.
For items without a proposal or tracking issue, an brief additional description is provided.
Each item should also have a reason indicating why it is necessary for async execution.
This list may be edited to add items if new requirements are identified.

- [ ] Transaction-level constraints:
    - [x] https://github.com/solana-foundation/solana-improvement-documents/pull/159
        - [x] https://github.com/anza-xyz/agave/issues/3245 
    - [x] https://github.com/solana-foundation/solana-improvement-documents/pull/191
    - [ ] https://github.com/solana-foundation/solana-improvement-documents/pull/192
    - [x] https://github.com/solana-foundation/solana-improvement-documents/pull/242
    - [ ] Allow for non-fee paying transactions to be included in blocks.
        - Description: Relax constraint that requires transactions to pay fees. This will allow for transactions to be included in blocks without requiring the fee to be paid. The transaction will not be executed, and potentially punish the leader for including the transaction.
        - Reason: Current validation of this constraint requires loading accounts.
    - [ ] Nonce Validity Relaxation
        - Description: Relax constraint that requires nonced-transactions to have a valid nonce, allowing us to skip account loading in validation. This will allow for transactions to be included in blocks without requiring the nonce to be valid. The transaction will not be executed, and potentially punish the leader for including the transaction.
        - Reason: Verifying nonce-validity requires loading the nonce account.
- [ ] Entry-level constraints:
    - [ ] https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0083-relax-entry-constraints.md
- [ ] Block-Level Changes
    - [ ] Block-limit changes
        - Description: Current block-limits require us to execute transactions to determine the actual number of CUs used. This must change, but no clear consensus on how to do this - currently leading idea is to used the requested CUs. Account limits must also change for ALT resolve to be fallible.
        - Reason: Requires execution of transactions to determine the actual number of CUs in the block.
