### ISSUE TITLE
Remove FeeRateGovernor

### ISSUE THREAD

**Issue by tao-stones** [anza-xyz/agave#3303]
move [discussion](https://github.com/anza-xyz/agave/pull/3211#issuecomment-2436255114) here, and maybe actions.

Details: 
`FeeRateGovernor` no longer determines to how transaction fee is calculated (except in tests where fee_rate_governor.lamports_per_siognature == 0 means to treat test transaction has zero fee). Instead transaction fee is calculated with `FeeStructure::default().lamports_per_signature`, which is statically `5_000`, so far.

`FeeRateGovernor` passed down through banks currently only serving two functions: 
1. burn transaction fee with its `burn_percent`, which is a const of 50%
2. enable zero_fee_for_test (which referenced PR was trying to address)

Tasks:
- [X] [PR #5216](https://github.com/anza-xyz/agave/pull/5216) to reduce usage of bank.fee-rate-governor.
- [X] [PR #5217](https://github.com/anza-xyz/agave/pull/5217) to reduce usage bank.fee_rate_governor, creating genesis_hash directly from genesis_config
- [X] [PR #5241](https://github.com/anza-xyz/agave/pull/5241) add comment to clarify private calculate_fee function of bank.
- [X] [PR #5290](https://github.com/anza-xyz/agave/pull/5290) relocate burning percent and logic to bank itself
- [ ] [PR #5749](https://github.com/anza-xyz/agave/pull/5749) Feature Gated: remove obsoleted FeeRateGovernor from fee calculation
- [ ] [PR #5388](https://github.com/anza-xyz/agave/pull/5388) remove bank.fee_rate_governor. 
     - do this ONLY when #5749 is activated everywhere.
- [ ] Issue #6191 
- [x] [PR #5399](https://github.com/anza-xyz/agave/pull/5399) refactor code to replace tuple with struct
