### ISSUE TITLE
Remove Legacy Banking Stage

### ISSUE THREAD

**Issue by apfitzge** [anza-xyz/agave#3357]
#### Problem
- In 2.1,  we added a warning that `thread-local-multi-iterator` block-production method would be deprecated (#3113)
- Now that we are on version 2.2, we should remove this variant from the `BlockProductionMethod` enum and remove supporting code

#### Proposed Solution

Likely this becomes a bit simpler once we also move forwarding to a separate stage: #3222 
This may sound simple, but is not that simple to do in the best way. And I propose the following plan for removing the variant and the associated code:

- [x] Remove `BlockProductionMethod::ThreadLocalMultiIterator` variant #3727
- [x] Remove `new_thread_local_multi_iterator` #3757
- [x] Remove `UnprocessedTransactionStorage`  #4604 
	- [x] we only ever need the `VoteStorage` variant now
	  - [x] remove get_min_priority, get_max_priority
	- [x] remove `ThreadLocalUnprocessedPackets`
	- [x] remove `message_hash_to_transaction`  #5233
	- [x] remove `multi_iterator_scanner.rs` #5292
- [x] Remove `ImmutableDeserializedPacket` innefficiency from Voting Threads #5362
- [ ] Remove `ConsumeScannerPayload` wrapper #5393
- [ ] #5072
